swagger: "2.0"
info:
  description: "Documentation about e-learning API"
  version: "1.0.0"
  title: "Swagger PFM"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "pfm.swagger.io"
basePath: "/api"
tags:
- name: "Training"
  description: "Resources to provide list of training and the training detail"

paths:
  /training:
    get:
      tags:
      - "Training"
      summary: "Finds all Trainings"
      description: ""
      operationId: "getAllTrainings"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Training"
        "400":
          description: "Invalid status value"

definitions:
  Training:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      createAt:
        type: "string"
        format: "date-time"
    xml:
      name: "Training"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
