swagger: "2.0"
info:
  description: "Documentation about e-learning API"
  version: "1.0.0"
  title: "Swagger PFM"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "pfm.swagger.io"
basePath: "/api"
tags:
- name: "Training"
  description: "Resources to provide list of training and the training detail"

paths:
  /training:
    get:
      tags:
      - "Training"
      summary: "Finds all Trainings"
      description: ""
      operationId: "getAllTrainings"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Training"
        "400":
          description: "Invalid status value"

definitions:
  Instructor:
    type: object
    properties:
      full_name:  
        type: string
      avatar:  
        type: string
      job_title:  
        type: string
      createdAt:  
        type: string
        format: date-time
      updatedAt:  
        type: string
        format: date-time
      id:  
        type: string
  Review:
    type: object
    properties:
      comment:     
        type: string
      rating:  
        type: integer
      training:    
        type: string
      createdAt:   
        type: string
        format: date-time
      updatedAt:   
        type: string
        format: date-time
      id:     
        type: string
  Training:
    type: object
    properties:
      id:
        type: string
      createdAt:    
        type: string
        format: date-time
      updatedAt:    
        type: string
        format: date-time
      title: 
        type: string
      description: 
        type: string
      cover_image:
        type: string
      cover_movie: 
        type: string
      number_subscribers:    
        type: number
      category:
        type: object
        properties:
          name:    
            type: string
      sub_category:
        type: object
        properties:
          name:    
            type: string
      attributes:
        type: object
        properties:
          video_content_length: 
            type: integer
            format: int64
          num_articles: 
            type: integer
            format: int64
          num_practice_tests: 
            type: integer
            format: int64
          has_lifetime_access:
            type:  boolean
          has_assignments:
            type: boolean
          has_certificate:
            type: boolean
      price:
        type: object
        properties: 
          amount: 
            type: number
            format: float
          currency: 
              type: string
          currency_symbol: 
              type: string
          price_string: 
              type: string
          is_free: 
            type: boolean
            default: false
      instructors:
        type: array
        items:
          $ref: '#/definitions/Instructor'
      reviews:
        type: array
        items:
          $ref: '#/definitions/Review'
    xml:
      name: "Training"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
